[package]
name = "crate-demo"
version = "0.1.0"
authors = ["sailor <sailor1@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restaurant={path="./restaurant"}